CREATE TABLE IF NOT EXISTS uploads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  original_filename VARCHAR(255) NOT NULL,
  file_path VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS output (
  id INT AUTO_INCREMENT PRIMARY KEY,
  upload_id INT NOT NULL,
  filename VARCHAR(255) NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  FOREIGN KEY (upload_id) REFERENCES uploads(id)
);
